# Generated by Django 2.1.5 on 2019-02-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
