# Generated by Django 2.1.5 on 2019-02-08 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0002_auto_20190208_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerteam',
            name='battle',
        ),
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(default=1, max_length=56),
        ),
    ]
