# Generated by Django 2.1.5 on 2019-02-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0003_auto_20190208_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='trainer_winner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='battle_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='battle_related',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='battle', to='battles.Battle'),
        ),
    ]
