# Generated by Django 2.1.6 on 2019-02-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('battles', '0005_auto_20190211_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerteam',
            name='pokemons',
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pkm_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkm_1', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pkm_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkm_2', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pkm_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pkm_3', to='pokemons.Pokemon'),
        ),
    ]
