# Generated by Django 2.1.6 on 2019-02-12 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0001_initial'),
        ('battles', '0006_auto_20190212_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerteam',
            name='pkm_1',
        ),
        migrations.RemoveField(
            model_name='trainerteam',
            name='pkm_2',
        ),
        migrations.RemoveField(
            model_name='trainerteam',
            name='pkm_3',
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pokemon_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_1', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pokemon_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_2', to='pokemons.Pokemon'),
        ),
        migrations.AddField(
            model_name='trainerteam',
            name='pokemon_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pokemon_3', to='pokemons.Pokemon'),
        ),
    ]
