# Generated by Django 2.1.7 on 2019-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0009_auto_20190322_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerteam',
            name='pokemon_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemons.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainerteam',
            name='pokemon_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemons.Pokemon'),
        ),
        migrations.AlterField(
            model_name='trainerteam',
            name='pokemon_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='pokemons.Pokemon'),
        ),
    ]
