# Generated by Django 2.1.7 on 2019-04-29 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0011_auto_20190327_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='status',
            field=models.CharField(default='ON_GOING', max_length=56),
        ),
    ]
