# Generated by Django 2.1.7 on 2019-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemons', '0002_auto_20190308_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='api_id',
            field=models.SmallIntegerField(verbose_name='PokeAPI Id'),
        ),
    ]
